### PR TITLE
Replaced div wrapper with list

### PR DESCRIPTION
**Pull request by shivanmodha**
Resolves 404 component rendering

### CODE REVIEW

**Comment by ryanmao725** [comment]
For some reason I can't checkout your branch?
I don't know if I'm doing something wrong.

**Comment by ryanisaacg** [comment]
> 
> 
> For some reason I can't checkout your branch?
> I don't know if I'm doing something wrong.

Might have something to do with the slash in the branchname

**Comment by shivanmodha** [comment]
`git fetch --all`

or

```
git branch fix/e404
git checkout fix/e404
git pull origin fix/e404
```

**Comment by shivanmodha** [comment]
Never had a problem with the slash before lol

**Comment by ryanmao725** [comment]
Got it, yeah.

**Comment by ryanmao725** [comment]
Looks good now, but I think we should fix the background behind the text. It looks a little weird being a different color.

**Comment by shivanmodha** [comment]
@ryanmao725 do you mean the darker red with the opacity?

**Comment by ryanmao725** [comment]
yes

**Comment by ryanmao725** [comment]
I meant like removing the red in general, and make it fully transparent?

**Comment by shivanmodha** [comment]
It is fully transparent, I'm not following

**Comment by ryanmao725** [comment]
image

**Comment by shivanmodha** [comment]
Did you pull down the latest, the opacity commit fixes that

**Comment by ryanmao725** [comment]
yeah, i don't know

**Pull request merged**
