### PR TITLE
Fix the major issues with the projector page

### PR DESCRIPTION
**Pull request by ryanisaacg**
Before:
image

After:
image

### CODE REVIEW

**Comment by thekabistro** [comment]
Add the hashtag?

**Comment by ryanisaacg** [comment]
> Add the hashtag?

Whoops, will do

**Comment by ryanisaacg** [comment]
image

**Comment by thekabistro** [comment]
Make 'em orange?

**Comment by shivanmodha** [comment]
Closing, Mao merged this with his last branch

**Pull request closed without merging**
