### PR TITLE
initial update of schedule

### PR DESCRIPTION
**Pull request by ryanmao725**
I'm not really sure how I feel about this schedule, let me know if you guys have any suggestions and I'll try to implement them.

### CODE REVIEW

**Comment by thekabistro** [comment]
Yes! Lovin it.  If you can make those timing adjustments I had asked for?

And if you think it'll look good do the split down the middle with two different boxes? Maybe...

**Comment by ryanmao725** [comment]
> Yes! Lovin it. If you can make those timing adjustments I had asked for?
> 
> And if you think it'll look good do the split down the middle with two different boxes? Maybe...

I thought I had made the changes to the schedule that you asked for. As for the split pane down the middle, I'm don't think that it would look too great.

**Comment by ryanmao725** [comment]
> > Yes! Lovin it. If you can make those timing adjustments I had asked for?
> > And if you think it'll look good do the split down the middle with two different boxes? Maybe...
> 
> I thought I had made the changes to the schedule that you asked for. As for the split pane down the middle, I'm don't think that it would look too great.

Nevermind, I was dumb and didn't add/commit the new one. Give me a second, I'm sorry.

**Comment by thekabistro** [comment]
You're gonna kill me, but I think I liked it better before.  This is my favorite version with the margins on the table.  I think keeping the `col-6` is worthwhile too instead of making it a `col-12` and that doesn't work well without the margins

image

**Comment by ryanmao725** [comment]
I think this is what you were asking for.. Same thing, let me know if there's anything you want changed.

**Comment by thekabistro** [comment]
Perfect!! Maybe add a little bit of margin on the bottom?

Fix the linting errors and then we're gooooood to merge.  Thanks, Ryan

**Comment by ryanmao725** [comment]
My current version has a margin at the bottom.
image

**Pull request merged**
