### PR TITLE
Login callback fix

### LINKED ISSUE #411: Request Deprecation
To fetch for the rest of the profile object

### PR DESCRIPTION
**Pull request by sejanep**
Resolves #411, #314

### CODE REVIEW

**Comment by shivanmodha** [comment]
This is in relation to #314

**Comment by shivanmodha** [comment]
What's the word on this one?

**Comment by zain08816** [comment]
> What's the word on this one?

It's still a WIP. I walked through how to troubleshoot/bugfix some issues, but only for one function. Jane is going to fix up any other functions involved in this.

**Review by shivanmodha — APPROVED** [review]
👍 LGTM

**Pull request merged**
