### PR TITLE
Believe to have fixed flashing issue

### PR DESCRIPTION
**Pull request by ryanmao725**
Addresses #288

### CODE REVIEW

**Comment by shivanmodha** [comment]
😱 - Testing this is gonna be difficult cause I don't cant replicate the env the bug was reported on

**Comment by shivanmodha** [comment]
Edge (win 10): 
image

**Review by shivanmodha — CHANGES_REQUESTED** [review]
Doesn't fix it on edge :(

**Comment by ryanmao725** [comment]
I think what Emily was referring to was the logo on the navbar would flash once before the animation would start again. My changes fixed that issue.

**Comment by emilywritescode** [comment]
^ +1

**Comment by shivanmodha** [comment]
Ahh ok, in that case if we deploy this to dev, @emilywritescode can you get your organizer to test this out?

**Comment by emilywritescode** [comment]
Sure, I’ll ping Kaushal

**Comment by ryanmao725** [comment]
The site is deployed to dev.hackru.org

**Comment by ryanmao725** [comment]
In terms of the edge issue, apparently it was fixed on version 3.0.0, but that is what we're running. Not sure how to fix that.

**Review by shivanmodha — APPROVED** [review]
Merging, but keeping the issue open

**Pull request merged**
