### PR TITLE
Profile Rework

### PR DESCRIPTION
**Pull request by zain08816**
Created the multi-component layout for profile

Parts still WIP:
- [X] Add more cards
- [X] Cleaning up components to only necessary parts
- [X] Add new questions, remove old
- [X] Redo updating user logic
- [X] implement check to see if everything is filled out
- [x] Add Waiver download, upload, and check
- [x] Add Slack input check
- [x] Arrangement?

### CODE REVIEW

**Comment by shivanmodha** [comment]
## Profile Forms
Each of the following is its own card with the following at the end:
 - Update button
 - Clear button

### About (@zain08816)
 - [x] First Name
 - [x] Last Name
 - [x] Number
 - [x] Date of Birth
 - [x] Shirt Size
 - [x] Gender
 - [x] Ethnicity (add "South Asian" in the dropdown as an option)

### Communication (@GabrielWeinbrenner)
 - [x] Slack ID
 - [x] GitHub Handle (optional field)

### Education (@zain08816)
 - [x] School (fix /r in school txt file)
 - [x] Graduation Year
 - [x] Level of Study
 - [x] Major

### A few questions (@zain08816)
 - [x] How many hackathons have you attended? (from old about)
 - [x] Anything we should account for?
 - [x] How did you hear about HackRU?
 - [x] What are your reasons for coming (Rank them from highest to lowest)
 - [x] What are you hoping to experience at HackRU?
 - [x] What are your initial thoughts on a virtual hackathon?
 - [x] Are you looking for team members?

### Documents (@GabrielWeinbrenner)
 - [x] Upload waiver (required) (button underneath to download waiver)
 - [x] Upload a resume (optional)


### MLH Notices (@zain08816)
 - [x] I have read and agree to the MLH Code of Conduct
 - [x] I authorize you to share my application/registration information for event administration, ranking, MLH administration, pre- and post-event informational e-mails, and occasional messages about hackathons in-line with the MLH Privacy Policy. Further, I agree to the terms of both the MLH Contest Terms and Conditions and the MLH Privacy Policy.
 - [x] Register Button

**Comment by shivanmodha** [comment]
```
3 Cards
 1. About, Education, A few questions, Polls, MLH Notices
 2. Communication
 3. Documents
 - Register Button!
```

**Comment by shivanmodha** [comment]
@zain08816 correct me if I'm wrong, but the "registration" logic still needs to be ironed out right?

**Comment by zain08816** [comment]
> @zain08816 correct me if I'm wrong, but the "registration" logic still needs to be ironed out right?
From my last testing, the registration logic should be working properly now

**Review by shivanmodha — APPROVED** [review]
Nice work!

**Pull request merged**
