### PR TITLE
Team Page

### PR DESCRIPTION
**Pull request by thekabistro**
image

https://dev.hackru.org/team

### CODE REVIEW

**Comment by ryanisaacg** [comment]
@thekabistro I think it looks a little weird that some people have the grey subtitle and some don't. Maybe we could add ones to everyone (like Shivan could have "Architect" or "Web Team Member") for uniformity?

**Comment by thekabistro** [comment]
Yeah. I was going to leave it up to specific teams. Alas it's all in the json configuration file.

**Comment by shivanmodha** [comment]
image
`and` is spelled incorrectly lol....twice.

Now for reals, looks great!

image
I can't put my finger on it, but I feel this looks a bit cluttered. Maybe if we moved the "Want to help organ..." part to the bottom of the page it'll look a bit better?

Also are there really 16 directors!?

**Comment by thekabistro** [comment]
Going to hold off on merging until we have a proper list of organizers in there.

**Pull request merged**
